"""
Report generation module for Excel and PDF outputs.

Generates professional reports from CR validation data suitable for
management reporting and change request documentation.
"""

from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, Optional

# Excel generation
try:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
    EXCEL_AVAILABLE = True
except ImportError:
    EXCEL_AVAILABLE = False

# PDF generation
try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, PageBreak
    from reportlab.platypus import Image as RLImage
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False


def generate_html_report(
    data: Dict[str, Any],
    output_path: str,
    logger: Optional[logging.Logger] = None
) -> None:
    """
    Generate HTML report from CR summary data.

    Creates a responsive, professional HTML report with:
    - Executive summary
    - Policy execution results
    - Patch compliance details
    - Device availability analysis
    - Failed devices list
    - Built-in CSS styling

    Args:
        data: CR summary data dictionary
        output_path: Path to save HTML file
        logger: Optional logger instance

    Raises:
        IOError: If file cannot be written
    """
    if logger:
        logger.info(f"Generating HTML report: {output_path}")

    html = _generate_html_content(data)

    # Write to file
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(html)

    if logger:
        logger.info(f"HTML report saved to {output_path}")


def _generate_html_content(data: Dict[str, Any]) -> str:
    """Generate complete HTML content for report."""
    cr_status = data.get('crStatus', {})
    is_successful = cr_status.get('successful', False)
    status_class = 'status-success' if is_successful else 'status-warning'
    status_text = '✓ CR SUCCESSFUL' if is_successful else '✗ CR NEEDS ATTENTION'

    html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Request Validation Report - {data.get('crName', 'N/A')}</title>
    <style>
        {_get_html_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>Change Request Validation Report</h1>
            <p class="subtitle">Generated: {data.get('generatedAt', 'N/A')}</p>
        </header>

        <section class="summary">
            <h2>Executive Summary</h2>
            <div class="info-grid">
                <div class="info-item">
                    <span class="label">CR Name:</span>
                    <span class="value">{data.get('crName', 'N/A')}</span>
                </div>
                <div class="info-item">
                    <span class="label">CR Window:</span>
                    <span class="value">{data.get('crWindow', {}).get('start', 'N/A')} → {data.get('crWindow', {}).get('end', 'N/A')}</span>
                </div>
                <div class="info-item">
                    <span class="label">Duration:</span>
                    <span class="value">{data.get('crWindow', {}).get('durationDays', 0)} days</span>
                </div>
                <div class="info-item">
                    <span class="label">Total Devices:</span>
                    <span class="value">{data.get('scope', {}).get('totalDevices', 0)}</span>
                </div>
            </div>

            <div class="status-badge {status_class}">
                {status_text}
            </div>

            {_generate_key_metrics_html(data)}
        </section>

        {_generate_policy_section_html(data)}
        {_generate_compliance_section_html(data)}
        {_generate_availability_section_html(data)}
        {_generate_issues_section_html(data)}
        {_generate_next_steps_section_html(data)}

        <footer>
            <p>Generated by Jamf Health Tool | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </footer>
    </div>
</body>
</html>
"""
    return html


def _get_html_styles() -> str:
    """Return CSS styles for HTML report."""
    return """
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #f5f5f7;
            padding: 20px;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }

        header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 3px solid #1F4E78;
        }

        h1 {
            color: #1F4E78;
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        h2 {
            color: #1F4E78;
            font-size: 1.8em;
            margin: 30px 0 20px 0;
            padding-bottom: 10px;
            border-bottom: 2px solid #e0e0e0;
        }

        h3 {
            color: #2c5282;
            font-size: 1.3em;
            margin: 20px 0 15px 0;
        }

        .subtitle {
            color: #666;
            font-size: 0.95em;
        }

        .summary {
            margin-bottom: 30px;
        }

        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 15px;
            margin-bottom: 30px;
        }

        .info-item {
            padding: 15px;
            background: #f8f9fa;
            border-radius: 8px;
            border-left: 4px solid #1F4E78;
        }

        .label {
            display: block;
            font-weight: 600;
            color: #666;
            font-size: 0.9em;
            margin-bottom: 5px;
        }

        .value {
            display: block;
            font-size: 1.1em;
            color: #333;
            font-weight: 500;
        }

        .status-badge {
            text-align: center;
            padding: 20px;
            border-radius: 8px;
            font-size: 1.5em;
            font-weight: bold;
            margin: 30px 0;
            color: white;
        }

        .status-success {
            background: linear-gradient(135deg, #00B050 0%, #00914A 100%);
        }

        .status-warning {
            background: linear-gradient(135deg, #FF6B6B 0%, #C92A2A 100%);
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
            background: white;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border-radius: 8px;
            overflow: hidden;
        }

        th {
            background: #1F4E78;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }

        td {
            padding: 12px;
            border-bottom: 1px solid #e0e0e0;
        }

        tr:hover {
            background: #f8f9fa;
        }

        .metric-card {
            background: #f8f9fa;
            padding: 20px;
            border-radius: 8px;
            margin: 15px 0;
            border-left: 4px solid #1F4E78;
        }

        .metric-value {
            font-size: 2em;
            font-weight: bold;
            color: #1F4E78;
            margin: 10px 0;
        }

        .rate-excellent {
            color: #00B050;
        }

        .rate-good {
            color: #FFA500;
        }

        .rate-poor {
            color: #FF0000;
        }

        .badge {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 12px;
            font-size: 0.85em;
            font-weight: 600;
        }

        .badge-success {
            background: #C6EFCE;
            color: #006100;
        }

        .badge-warning {
            background: #FFEB9C;
            color: #9C5700;
        }

        .badge-danger {
            background: #FFC7CE;
            color: #9C0006;
        }

        .recommendations {
            background: #E7F3FF;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #0066CC;
            margin: 20px 0;
        }

        .recommendations ul {
            list-style-position: inside;
            margin-left: 0;
        }

        .recommendations li {
            margin: 8px 0;
            padding-left: 10px;
        }

        footer {
            margin-top: 50px;
            padding-top: 20px;
            border-top: 2px solid #e0e0e0;
            text-align: center;
            color: #666;
            font-size: 0.9em;
        }

        section {
            margin: 40px 0;
        }

        @media print {
            body {
                background: white;
                padding: 0;
            }

            .container {
                box-shadow: none;
                padding: 20px;
            }

            .status-badge {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }

            th {
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }
        }
    """


def _generate_key_metrics_html(data: Dict[str, Any]) -> str:
    """Generate key metrics cards."""
    metrics = []

    patch = data.get('patchCompliance', {})
    if patch:
        compliance = patch.get('overallCompliance', 0)
        rate_class = 'rate-excellent' if compliance >= 95 else 'rate-good' if compliance >= 85 else 'rate-poor'
        metrics.append(f"""
        <div class="metric-card">
            <strong>Overall Compliance</strong>
            <div class="metric-value {rate_class}">{compliance:.1f}%</div>
        </div>
        """)

    avail = data.get('deviceAvailability', {})
    if avail:
        online_pct = avail.get('onlineDuringWindow', {}).get('percentage', 0)
        rate_class = 'rate-excellent' if online_pct >= 90 else 'rate-good' if online_pct >= 75 else 'rate-poor'
        metrics.append(f"""
        <div class="metric-card">
            <strong>Devices Online During Window</strong>
            <div class="metric-value {rate_class}">{online_pct:.1f}%</div>
        </div>
        """)

    return ''.join(metrics) if metrics else ''


def _generate_policy_section_html(data: Dict[str, Any]) -> str:
    """Generate policy execution section."""
    policy_exec = data.get('policyExecution', {})
    policies = policy_exec.get('summary', [])

    if not policies:
        return ''

    rows = []
    for policy in policies:
        total = policy.get('devicesInScope', 0)
        completed = policy.get('completed', 0)
        success_rate = (completed / total * 100) if total > 0 else 0

        badge_class = 'badge-success' if success_rate >= 95 else 'badge-warning' if success_rate >= 85 else 'badge-danger'

        rows.append(f"""
        <tr>
            <td>{policy.get('policyId')}</td>
            <td>{policy.get('policyName', 'N/A')}</td>
            <td style="text-align: center;">{'Yes' if policy.get('enabled') else 'No'}</td>
            <td style="text-align: center;">{total}</td>
            <td style="text-align: center;">{completed}</td>
            <td style="text-align: center;">{policy.get('failed', 0)}</td>
            <td style="text-align: center;"><span class="badge {badge_class}">{success_rate:.1f}%</span></td>
        </tr>
        """)

    return f"""
    <section>
        <h2>Policy Execution Results</h2>
        <table>
            <thead>
                <tr>
                    <th>Policy ID</th>
                    <th>Policy Name</th>
                    <th>Enabled</th>
                    <th>In Scope</th>
                    <th>Completed</th>
                    <th>Failed</th>
                    <th>Success Rate</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
    </section>
    """


def _generate_compliance_section_html(data: Dict[str, Any]) -> str:
    """Generate patch compliance section."""
    patch = data.get('patchCompliance', {})
    if not patch:
        return ''

    targets = patch.get('targets', [])
    if not targets:
        return ''

    rows = []
    for target_result in targets:
        target_info = target_result.get('target', {})
        rate = target_result.get('complianceRate', 0)
        badge_class = 'badge-success' if rate >= 95 else 'badge-warning' if rate >= 85 else 'badge-danger'
        non_compliant = target_result.get('nonCompliant', target_result.get('outdated', 0))

        rows.append(f"""
        <tr>
            <td>{target_info.get('name', 'N/A')}</td>
            <td style="text-align: center;">{target_info.get('type', 'N/A')}</td>
            <td style="text-align: center;">{target_info.get('minVersion', 'N/A')}</td>
            <td style="text-align: center;">{target_result.get('total', 0)}</td>
            <td style="text-align: center;">{target_result.get('compliant', 0)}</td>
            <td style="text-align: center;">{non_compliant}</td>
            <td style="text-align: center;"><span class="badge {badge_class}">{rate:.1f}%</span></td>
        </tr>
        """)

    return f"""
    <section>
        <h2>Patch Compliance</h2>
        <p><strong>Overall Compliance:</strong> {patch.get('overallCompliance', 0):.1f}%</p>
        <table>
            <thead>
                <tr>
                    <th>Target</th>
                    <th>Type</th>
                    <th>Version</th>
                    <th>Total</th>
                    <th>Compliant</th>
                    <th>Non-Compliant</th>
                    <th>Rate</th>
                </tr>
            </thead>
            <tbody>
                {''.join(rows)}
            </tbody>
        </table>
    </section>
    """


def _generate_availability_section_html(data: Dict[str, Any]) -> str:
    """Generate device availability section."""
    avail = data.get('deviceAvailability', {})
    if not avail:
        return ''

    online = avail.get('onlineDuringWindow', {})
    offline = avail.get('offlineDuringWindow', {})

    return f"""
    <section>
        <h2>Device Availability</h2>
        <table>
            <thead>
                <tr>
                    <th>Category</th>
                    <th style="text-align: center;">Count</th>
                    <th style="text-align: center;">Percentage</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Online During Window</td>
                    <td style="text-align: center;">{online.get('count', 0)}</td>
                    <td style="text-align: center;"><span class="badge badge-success">{online.get('percentage', 0):.1f}%</span></td>
                </tr>
                <tr>
                    <td>Offline During Window</td>
                    <td style="text-align: center;">{offline.get('count', 0)}</td>
                    <td style="text-align: center;"><span class="badge badge-danger">{offline.get('percentage', 0):.1f}%</span></td>
                </tr>
            </tbody>
        </table>

        {_generate_recommendations_html(avail.get('recommendations', []))}
    </section>
    """


def _generate_issues_section_html(data: Dict[str, Any]) -> str:
    """Generate issues section."""
    cr_status = data.get('crStatus', {})
    issues = cr_status.get('issues', [])

    if not issues:
        return ''

    issue_items = ''.join([f'<li>{issue}</li>' for issue in issues])

    return f"""
    <section>
        <h2>Issues Requiring Attention</h2>
        <div class="recommendations" style="background: #FFE7E7; border-left-color: #FF0000;">
            <ul>
                {issue_items}
            </ul>
        </div>
    </section>
    """


def _generate_next_steps_section_html(data: Dict[str, Any]) -> str:
    """Generate next steps section."""
    cr_status = data.get('crStatus', {})
    next_steps = cr_status.get('nextSteps', [])

    if not next_steps:
        return ''

    step_items = ''.join([f'<li>{step}</li>' for step in next_steps])

    return f"""
    <section>
        <h2>Next Steps</h2>
        <div class="recommendations">
            <ol>
                {step_items}
            </ol>
        </div>
    </section>
    """


def _generate_recommendations_html(recommendations: list) -> str:
    """Generate recommendations box."""
    if not recommendations:
        return ''

    rec_items = ''.join([f'<li>{rec}</li>' for rec in recommendations])

    return f"""
    <div class="recommendations">
        <strong>Recommendations:</strong>
        <ul>
            {rec_items}
        </ul>
    </div>
    """


def generate_excel_report(
    data: Dict[str, Any],
    output_path: str,
    logger: Optional[logging.Logger] = None
) -> None:
    """
    Generate Excel report from CR summary data.

    Creates a multi-sheet workbook with:
    - Executive Summary
    - Policy Execution Results
    - Patch Compliance Details
    - Device Availability
    - Failed Devices (for follow-up)

    Args:
        data: CR summary data dictionary
        output_path: Path to save Excel file
        logger: Optional logger instance

    Raises:
        ImportError: If openpyxl is not installed
        IOError: If file cannot be written
    """
    if not EXCEL_AVAILABLE:
        raise ImportError(
            "openpyxl is required for Excel report generation. "
            "Install with: pip install openpyxl"
        )

    if logger:
        logger.info(f"Generating Excel report: {output_path}")

    wb = Workbook()

    # Remove default sheet
    if "Sheet" in wb.sheetnames:
        del wb["Sheet"]

    # Create sheets
    _create_summary_sheet(wb, data)
    _create_policy_sheet(wb, data)
    _create_compliance_sheet(wb, data)
    _create_availability_sheet(wb, data)
    _create_failed_devices_sheet(wb, data)

    # Save workbook
    wb.save(output_path)

    if logger:
        logger.info(f"Excel report saved to {output_path}")


def _create_summary_sheet(wb: Workbook, data: Dict[str, Any]) -> None:
    """Create executive summary sheet."""
    ws = wb.create_sheet("Executive Summary", 0)

    # Header styling
    header_fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
    header_font = Font(color="FFFFFF", bold=True, size=14)

    # Title
    ws['A1'] = "Change Request Validation Report"
    ws['A1'].font = Font(bold=True, size=16)
    ws.merge_cells('A1:D1')

    # CR Info
    row = 3
    ws[f'A{row}'] = "CR Name:"
    ws[f'A{row}'].font = Font(bold=True)
    ws[f'B{row}'] = data.get('crName', 'N/A')

    row += 1
    ws[f'A{row}'] = "Generated:"
    ws[f'A{row}'].font = Font(bold=True)
    ws[f'B{row}'] = data.get('generatedAt', 'N/A')

    row += 1
    cr_window = data.get('crWindow', {})
    ws[f'A{row}'] = "CR Window:"
    ws[f'A{row}'].font = Font(bold=True)
    ws[f'B{row}'] = f"{cr_window.get('start', 'N/A')} → {cr_window.get('end', 'N/A')}"

    row += 1
    ws[f'A{row}'] = "Duration:"
    ws[f'A{row}'].font = Font(bold=True)
    ws[f'B{row}'] = f"{cr_window.get('durationDays', 0)} days"

    # CR Status (prominent)
    row += 2
    cr_status = data.get('crStatus', {})
    status_text = "✓ SUCCESSFUL" if cr_status.get('successful') else "✗ NEEDS ATTENTION"
    status_color = "00B050" if cr_status.get('successful') else "FF0000"

    ws[f'A{row}'] = "Overall Status:"
    ws[f'A{row}'].font = Font(bold=True, size=12)
    ws[f'B{row}'] = status_text
    ws[f'B{row}'].font = Font(bold=True, size=12, color="FFFFFF")
    ws[f'B{row}'].fill = PatternFill(start_color=status_color, end_color=status_color, fill_type="solid")
    ws[f'B{row}'].alignment = Alignment(horizontal='center')

    # Metrics table
    row += 2
    ws[f'A{row}'] = "Key Metrics"
    ws[f'A{row}'].font = Font(bold=True, size=12)
    ws[f'A{row}'].fill = header_fill
    ws.merge_cells(f'A{row}:D{row}')

    row += 1
    scope = data.get('scope', {})
    ws[f'A{row}'] = "Total Devices"
    ws[f'B{row}'] = scope.get('totalDevices', 0)

    row += 1
    ws[f'A{row}'] = "Success Threshold"
    ws[f'B{row}'] = f"{data.get('successThreshold', 0.95) * 100:.0f}%"

    # Patch compliance
    patch = data.get('patchCompliance', {})
    if patch:
        row += 1
        ws[f'A{row}'] = "Overall Compliance"
        compliance = patch.get('overallCompliance', 0)
        ws[f'B{row}'] = f"{compliance:.1f}%"
        ws[f'B{row}'].font = Font(bold=True)

        # Color code based on success threshold
        threshold = data.get('successThreshold', 0.95) * 100
        if compliance >= threshold:
            ws[f'B{row}'].fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
        else:
            ws[f'B{row}'].fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")

    # Device availability
    avail = data.get('availability', data.get('deviceAvailability', {}))
    if avail:
        row += 1
        online = avail.get('onlineEntireWindow', {}).get('percentage', 0)
        ws[f'A{row}'] = "Devices Online During Window"
        ws[f'B{row}'] = f"{online:.1f}%"

    # Auto-size columns
    ws.column_dimensions['A'].width = 30
    ws.column_dimensions['B'].width = 40


def _create_policy_sheet(wb: Workbook, data: Dict[str, Any]) -> None:
    """Create policy execution results sheet."""
    ws = wb.create_sheet("Policy Execution")

    # Headers
    headers = ["Policy ID", "Policy Name", "Enabled", "Devices in Scope",
               "Completed", "Failed", "Pending", "Offline", "Success Rate"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")
        cell.alignment = Alignment(horizontal='center')

    # Data
    policy_exec = data.get('policyExecution', {})
    policies = policy_exec.get('summary', [])

    row = 2
    for policy in policies:
        ws.cell(row=row, column=1, value=policy.get('policyId'))
        ws.cell(row=row, column=2, value=policy.get('policyName'))
        ws.cell(row=row, column=3, value="Yes" if policy.get('enabled') else "No")
        ws.cell(row=row, column=4, value=policy.get('devicesInScope', 0))
        ws.cell(row=row, column=5, value=policy.get('completed', 0))
        ws.cell(row=row, column=6, value=policy.get('failed', 0))
        ws.cell(row=row, column=7, value=policy.get('pending', 0))
        ws.cell(row=row, column=8, value=policy.get('offline', 0))

        # Calculate success rate
        total = policy.get('devicesInScope', 0)
        completed = policy.get('completed', 0)
        success_rate = (completed / total * 100) if total > 0 else 0

        cell = ws.cell(row=row, column=9, value=f"{success_rate:.1f}%")

        # Color code success rate
        if success_rate >= 95:
            cell.fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
        elif success_rate >= 85:
            cell.fill = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
        else:
            cell.fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")

        row += 1

    # Auto-size columns
    for col in range(1, 10):
        ws.column_dimensions[get_column_letter(col)].width = 15
    ws.column_dimensions['B'].width = 30


def _create_compliance_sheet(wb: Workbook, data: Dict[str, Any]) -> None:
    """Create patch compliance details sheet."""
    ws = wb.create_sheet("Patch Compliance")

    patch = data.get('patchCompliance', {})
    if not patch:
        ws['A1'] = "No patch compliance data available"
        return

    # Summary
    ws['A1'] = "Patch Compliance Summary"
    ws['A1'].font = Font(bold=True, size=14)

    row = 3
    ws[f'A{row}'] = "Overall Compliance:"
    ws[f'A{row}'].font = Font(bold=True)
    compliance = patch.get('overallCompliance', 0)
    ws[f'B{row}'] = f"{compliance:.1f}%"
    ws[f'B{row}'].font = Font(bold=True)

    # Targets table
    row += 2
    headers = ["Target", "Type", "Version", "Total Devices", "Compliant", "Non-Compliant", "Compliance Rate"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=row, column=col, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="1F4E78", end_color="1F4E78", fill_type="solid")

    row += 1
    for target_result in patch.get('targets', []):
        target_info = target_result.get('target', {})
        ws.cell(row=row, column=1, value=target_info.get('name'))
        ws.cell(row=row, column=2, value=target_info.get('type'))
        ws.cell(row=row, column=3, value=target_info.get('minVersion'))
        ws.cell(row=row, column=4, value=target_result.get('total', 0))
        ws.cell(row=row, column=5, value=target_result.get('compliant', 0))

        non_compliant = target_result.get('nonCompliant', target_result.get('outdated', 0))
        ws.cell(row=row, column=6, value=non_compliant)

        rate = target_result.get('complianceRate', 0)
        cell = ws.cell(row=row, column=7, value=f"{rate:.1f}%")

        # Color code
        if rate >= 95:
            cell.fill = PatternFill(start_color="C6EFCE", end_color="C6EFCE", fill_type="solid")
        elif rate >= 85:
            cell.fill = PatternFill(start_color="FFEB9C", end_color="FFEB9C", fill_type="solid")
        else:
            cell.fill = PatternFill(start_color="FFC7CE", end_color="FFC7CE", fill_type="solid")

        row += 1

    # Auto-size columns
    for col in range(1, 8):
        ws.column_dimensions[get_column_letter(col)].width = 18


def _create_availability_sheet(wb: Workbook, data: Dict[str, Any]) -> None:
    """Create device availability sheet."""
    ws = wb.create_sheet("Device Availability")

    avail = data.get('deviceAvailability', {})
    if not avail:
        ws['A1'] = "No device availability data available"
        return

    # Summary
    ws['A1'] = "Device Availability During CR Window"
    ws['A1'].font = Font(bold=True, size=14)

    row = 3
    scope = data.get('scope', {})
    ws[f'A{row}'] = "Total Devices:"
    ws[f'A{row}'].font = Font(bold=True)
    ws[f'B{row}'] = scope.get('totalDevices', 0)

    # Availability breakdown
    row += 2
    categories = [
        ('onlineDuringWindow', 'Online During Window', '00B050'),
        ('offlineDuringWindow', 'Offline During Window', 'FF0000'),
    ]

    for key, label, color in categories:
        cat_data = avail.get(key, {})
        count = cat_data.get('count', 0)
        pct = cat_data.get('percentage', 0)

        ws[f'A{row}'] = label
        ws[f'A{row}'].font = Font(bold=True)
        ws[f'B{row}'] = f"{count} ({pct:.1f}%)"
        ws[f'B{row}'].fill = PatternFill(start_color=color, end_color=color, fill_type="solid")
        ws[f'B{row}'].font = Font(color="FFFFFF" if color in ['00B050', 'FF0000'] else "000000")

        row += 1

    # Recommendations
    row += 2
    ws[f'A{row}'] = "Recommendations:"
    ws[f'A{row}'].font = Font(bold=True, size=12)

    row += 1
    for rec in data.get('deviceAvailability', {}).get('recommendations', []):
        ws[f'A{row}'] = f"• {rec}"
        ws.merge_cells(f'A{row}:D{row}')
        row += 1

    # Auto-size columns
    ws.column_dimensions['A'].width = 30
    ws.column_dimensions['B'].width = 30


def _create_failed_devices_sheet(wb: Workbook, data: Dict[str, Any]) -> None:
    """Create failed devices list for follow-up."""
    ws = wb.create_sheet("Failed Devices")

    # Headers
    headers = ["Computer ID", "Computer Name", "Serial", "Policy ID", "Policy Name", "Status", "Error"]
    for col, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill(start_color="C00000", end_color="C00000", fill_type="solid")

    # Data
    failed_devices = data.get('policyExecution', {}).get('failedDevices', [])

    if not failed_devices:
        ws['A2'] = "No failed devices - CR successful!"
        ws['A2'].font = Font(color="00B050", bold=True)
        ws.merge_cells('A2:G2')
        return

    row = 2
    for device in failed_devices:
        ws.cell(row=row, column=1, value=device.get('computerId'))
        ws.cell(row=row, column=2, value=device.get('computerName'))
        ws.cell(row=row, column=3, value=device.get('serial', 'N/A'))
        ws.cell(row=row, column=4, value=device.get('policyId'))
        ws.cell(row=row, column=5, value=device.get('policyName', 'N/A'))
        ws.cell(row=row, column=6, value=device.get('status', 'Failed'))
        ws.cell(row=row, column=7, value=device.get('error', 'N/A'))

        # Highlight failed rows
        for col in range(1, 8):
            ws.cell(row=row, column=col).fill = PatternFill(
                start_color="FFC7CE", end_color="FFC7CE", fill_type="solid"
            )

        row += 1

    # Auto-size columns
    for col in range(1, 8):
        ws.column_dimensions[get_column_letter(col)].width = 18
    ws.column_dimensions['B'].width = 30
    ws.column_dimensions['G'].width = 40


def generate_pdf_report(
    data: Dict[str, Any],
    output_path: str,
    logger: Optional[logging.Logger] = None
) -> None:
    """
    Generate PDF report from CR summary data.

    Creates a professional PDF report with:
    - Executive summary page
    - Policy execution results
    - Patch compliance details
    - Device availability analysis
    - Failed devices list

    Args:
        data: CR summary data dictionary
        output_path: Path to save PDF file
        logger: Optional logger instance

    Raises:
        ImportError: If reportlab is not installed
        IOError: If file cannot be written
    """
    if not PDF_AVAILABLE:
        raise ImportError(
            "reportlab is required for PDF report generation. "
            "Install with: pip install reportlab"
        )

    if logger:
        logger.info(f"Generating PDF report: {output_path}")

    # Create PDF
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1F4E78'),
        spaceAfter=30,
        alignment=TA_CENTER
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#1F4E78'),
        spaceAfter=12,
        spaceBefore=12
    )

    # Title
    story.append(Paragraph("Change Request Validation Report", title_style))
    story.append(Spacer(1, 0.2*inch))

    # Executive Summary
    _add_pdf_summary(story, data, styles, heading_style)
    story.append(PageBreak())

    # Policy Execution
    _add_pdf_policy_section(story, data, styles, heading_style)
    story.append(PageBreak())

    # Patch Compliance
    _add_pdf_compliance_section(story, data, styles, heading_style)
    story.append(PageBreak())

    # Device Availability
    _add_pdf_availability_section(story, data, styles, heading_style)

    # Failed Devices (if any)
    failed_devices = data.get('policyExecution', {}).get('failedDevices', [])
    if failed_devices:
        story.append(PageBreak())
        _add_pdf_failed_devices(story, data, styles, heading_style)

    # Build PDF
    doc.build(story)

    if logger:
        logger.info(f"PDF report saved to {output_path}")


def _add_pdf_summary(story, data, styles, heading_style):
    """Add executive summary to PDF."""
    story.append(Paragraph("Executive Summary", heading_style))

    # CR Info table
    cr_info = [
        ["CR Name:", data.get('crName', 'N/A')],
        ["Generated:", data.get('generatedAt', 'N/A')],
        ["CR Window:", f"{data.get('crWindow', {}).get('start', 'N/A')} → {data.get('crWindow', {}).get('end', 'N/A')}"],
        ["Duration:", f"{data.get('crWindow', {}).get('durationDays', 0)} days"],
    ]

    t = Table(cr_info, colWidths=[2*inch, 4*inch])
    t.setStyle(TableStyle([
        ('FONT', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONT', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*inch))

    # Status badge
    cr_status = data.get('crStatus', {})
    status_text = "✓ CR SUCCESSFUL" if cr_status.get('successful') else "✗ CR NEEDS ATTENTION"
    status_color = colors.HexColor('#00B050') if cr_status.get('successful') else colors.HexColor('#FF0000')

    status_table = [[status_text]]
    t = Table(status_table, colWidths=[6*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), status_color),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
        ('FONT', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 16),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*inch))

    # Key metrics
    metrics = [
        ["Metric", "Value"],
        ["Total Devices", str(data.get('scope', {}).get('totalDevices', 0))],
        ["Success Threshold", f"{data.get('successThreshold', 0.95) * 100:.0f}%"],
    ]

    patch = data.get('patchCompliance', {})
    if patch:
        compliance = patch.get('overallCompliance', 0)
        metrics.append(["Overall Compliance", f"{compliance:.1f}%"])

    avail = data.get('deviceAvailability', {})
    if avail:
        online = avail.get('onlineEntireWindow', {}).get('percentage', 0)
        metrics.append(["Devices Online During Window", f"{online:.1f}%"])

    t = Table(metrics, colWidths=[3*inch, 3*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONT', (0, 1), (0, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(t)


def _add_pdf_policy_section(story, data, styles, heading_style):
    """Add policy execution results to PDF."""
    story.append(Paragraph("Policy Execution Results", heading_style))

    policy_exec = data.get('policyExecution', {})
    policies = policy_exec.get('summary', [])

    if not policies:
        story.append(Paragraph("No policy execution data available.", styles['Normal']))
        return

    # Build table
    table_data = [["Policy ID", "Policy Name", "In Scope", "Completed", "Failed", "Success Rate"]]

    for policy in policies:
        total = policy.get('devicesInScope', 0)
        completed = policy.get('completed', 0)
        success_rate = (completed / total * 100) if total > 0 else 0

        table_data.append([
            str(policy.get('policyId')),
            policy.get('policyName', 'N/A')[:30],  # Truncate long names
            str(total),
            str(completed),
            str(policy.get('failed', 0)),
            f"{success_rate:.1f}%"
        ])

    t = Table(table_data, colWidths=[0.8*inch, 2.2*inch, 0.8*inch, 1*inch, 0.8*inch, 1*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (1, 1), (1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))

    # Add conditional coloring for success rates
    for i, policy in enumerate(policies, 1):
        total = policy.get('devicesInScope', 0)
        completed = policy.get('completed', 0)
        success_rate = (completed / total * 100) if total > 0 else 0

        if success_rate >= 95:
            color = colors.HexColor('#C6EFCE')
        elif success_rate >= 85:
            color = colors.HexColor('#FFEB9C')
        else:
            color = colors.HexColor('#FFC7CE')

        t.setStyle(TableStyle([('BACKGROUND', (5, i), (5, i), color)]))

    story.append(t)


def _add_pdf_compliance_section(story, data, styles, heading_style):
    """Add patch compliance details to PDF."""
    story.append(Paragraph("Patch Compliance Details", heading_style))

    patch = data.get('patchCompliance', {})
    if not patch:
        story.append(Paragraph("No patch compliance data available.", styles['Normal']))
        return

    # Overall compliance
    compliance = patch.get('overallCompliance', 0)
    story.append(Paragraph(f"<b>Overall Compliance:</b> {compliance:.1f}%", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))

    # Targets table
    table_data = [["Target", "Type", "Version", "Compliant", "Non-Compliant", "Rate"]]

    for target_result in patch.get('targets', []):
        target_info = target_result.get('target', {})
        non_compliant = target_result.get('nonCompliant', target_result.get('outdated', 0))
        rate = target_result.get('complianceRate', 0)

        table_data.append([
            target_info.get('name', 'N/A'),
            target_info.get('type', 'N/A'),
            target_info.get('minVersion', 'N/A'),
            str(target_result.get('compliant', 0)),
            str(non_compliant),
            f"{rate:.1f}%"
        ])

    t = Table(table_data, colWidths=[1.5*inch, 1*inch, 1*inch, 1*inch, 1.2*inch, 0.8*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (0, 1), (0, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))

    story.append(t)


def _add_pdf_availability_section(story, data, styles, heading_style):
    """Add device availability analysis to PDF."""
    story.append(Paragraph("Device Availability Analysis", heading_style))

    avail = data.get('deviceAvailability', {})
    if not avail:
        story.append(Paragraph("No device availability data available.", styles['Normal']))
        return

    # Availability breakdown
    table_data = [["Category", "Count", "Percentage"]]

    categories = [
        ('onlineDuringWindow', 'Online During Window'),
        ('offlineDuringWindow', 'Offline During Window'),
    ]

    for key, label in categories:
        cat_data = avail.get(key, {})
        count = cat_data.get('count', 0)
        pct = cat_data.get('percentage', 0)

        table_data.append([label, str(count), f"{pct:.1f}%"])

    t = Table(table_data, colWidths=[3*inch, 1.5*inch, 1.5*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F4E78')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('ALIGN', (0, 0), (0, -1), 'LEFT'),
        ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
    ]))

    story.append(t)
    story.append(Spacer(1, 0.2*inch))

    # Recommendations
    recommendations = avail.get('recommendations', [])
    if recommendations:
        story.append(Paragraph("<b>Recommendations:</b>", styles['Normal']))
        for rec in recommendations:
            story.append(Paragraph(f"• {rec}", styles['Normal']))


def _add_pdf_failed_devices(story, data, styles, heading_style):
    """Add failed devices list to PDF."""
    story.append(Paragraph("Failed Devices (Require Follow-up)", heading_style))

    failed_devices = data.get('policyExecution', {}).get('failedDevices', [])

    if not failed_devices:
        story.append(Paragraph("No failed devices - CR successful!", styles['Normal']))
        return

    # Limit to first 50 devices (to avoid huge PDFs)
    display_devices = failed_devices[:50]

    table_data = [["Computer ID", "Computer Name", "Serial", "Policy ID", "Status"]]

    for device in display_devices:
        table_data.append([
            str(device.get('computerId', 'N/A')),
            device.get('computerName', 'N/A')[:25],  # Truncate long names
            device.get('serial', 'N/A'),
            str(device.get('policyId', 'N/A')),
            device.get('status', 'Failed')
        ])

    t = Table(table_data, colWidths=[1*inch, 2*inch, 1.2*inch, 0.8*inch, 1*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#C00000')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (1, 1), (1, -1), 'LEFT'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 3),
        ('RIGHTPADDING', (0, 0), (-1, -1), 3),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
    ]))

    story.append(t)

    if len(failed_devices) > 50:
        story.append(Spacer(1, 0.2*inch))
        story.append(Paragraph(
            f"<i>Note: Showing first 50 of {len(failed_devices)} failed devices. "
            "See JSON output for complete list.</i>",
            styles['Normal']
        ))
